server:
  port: 8070
dubbo:
  application:
    name: user-server
  registry:
    address:
  protocol:
    name: dubbo
    port: 9991
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/gmall?serverTimezone=UTC&characterEncoding=UTF-8
