server:
  port: 8080
dubbo:
  application:
    name: user-web
  registry:
    address: zookeeper://192.168.1.6:2181

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmall
    password: root
    username: root
